blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/Zhylon/zhylon-cli/pulls
    about: 'For ideas or feature requests, send in a pull request'
  - name: Documentation issue
    url: https://github.com/Zhylon/zhylon-cli
    about: For documentation issues, open a pull request to the readme
